name: dpr
recipe: drupal8
config:
  webroot: web
  php: '7.4'
  composer_version: '1.10.22'
  xdebug: false
  database: 'mariadb:10.5'
services:
  database:
    type: 'mariadb:10.5'
    portforward: 33061
    creds:
      user: drupal8
      password: drupal8
  database2:
    type: 'mariadb:10.5'
    portforward: 33062
    creds:
      user: drupal8
      password: drupal8
